version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
exclude_patterns:
  - "UI"
  - "Server/tests"
checks:
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: true
  identical-code:
    enabled: false