language: node_js
node_js:
  - "9"

services:
  - postgresql

before_install:
  - npm install -g npm@latest

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

after_success: npm run coverage
